// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 06/12/2024, 20:23:11
const configMerger = require("/Users/kairos/Documents/GitHub/Chronos/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.cjs")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/kairos/Documents/GitHub/Chronos/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kairos/Documents/GitHub/Chronos/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kairos/Documents/GitHub/Chronos/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kairos/Documents/GitHub/Chronos/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kairos/Documents/GitHub/Chronos/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kairos/Documents/GitHub/Chronos/plugins/**/*.{js,ts,mjs}","/Users/kairos/Documents/GitHub/Chronos/composables/**/*.{js,ts,mjs}","/Users/kairos/Documents/GitHub/Chronos/utils/**/*.{js,ts,mjs}","/Users/kairos/Documents/GitHub/Chronos/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/kairos/Documents/GitHub/Chronos/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/kairos/Documents/GitHub/Chronos/app.config.{js,ts,mjs}"] } }));

module.exports = (() => {const cfg=config;cfg["content"]["files"]["21"] = "/Users/kairos/Documents/GitHub/Chronos/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})()
